CFLAGS = -Wall

all:
	make exo1
	make exo2
	make exo4
	make exo5

exo1: exo1.c
	gcc $< -o $@ $(CFLAGS)

exo2: exo2.c
	gcc $< -o $@ $(CFLAGS)

exo4: exo4.c
	gcc $< -o $@ $(CFLAGS)
	
exo5: exo5.c
	gcc $< -o $@ $(CFLAGS)
